"""Add Tenant and NotificationHistory models

Revision ID: aa2c8fc7fd95
Revises: 
Create Date: 2025-05-02 11:53:42.769932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'aa2c8fc7fd95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_sid'), ['sid'], unique=True)

    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hoa_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('hoa_contact_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access_notes', sa.Text(), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_column('zip')
        batch_op.drop_column('state')
        batch_op.drop_column('address')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('properties', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('address', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.CHAR(length=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('zip', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('name',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.drop_column('access_notes')
        batch_op.drop_column('hoa_contact_info')
        batch_op.drop_column('hoa_name')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sid'))

    # ### end Alembic commands ###
